In [13]:
import numpy as np
def two(x):
    """(float, int) -> (float, int); array -> 
array"""
    if isinstance(x, (float, int)):
        result = 2
    elif isinstance(x, np.ndarray):
        result = np.zeros(x.shape, x.dtype) + 2
    else:
        result = 'ERROR: Invalid type!'
    return result
print(two(np.array([1,2,3,45])))
print(two(np.array([1,2,3.5,45])))

[2 2 2 2]
[2. 2. 2. 2.]


In [ ]:
import numpy as np


In [133]:
import numpy as np
ar = np.linspace(1,12,12).reshape(3,4`)
print(ar)
print(ar.shape)
print(ar.size)
print(len(ar)) 

                                  

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
(3, 4)
12
3
