In [5]:
a = [2,4,6,8]
b = [3,5,7,9]
add = a + b
sub = a - b
mul = a * b
print(mul)

[2, 4, 6, 8, 3, 5, 7, 9]


In [19]:
import numpy as np
a = np.array([2,4,6,8])
b = np.array([3,5,7,9])

add = a+b
sub = a-b
mul = a*b
div = a/b
rem = a%b
print("add: ",add)
print("sub: ",sub)
print("mul: ",mul)
print("div: ",div)
print("rem: ",rem)

add:  [ 5  9 13 17]
sub:  [-1 -1 -1 -1]
mul:  [ 6 20 42 72]
div:  [0.66666667 0.8        0.85714286 0.88888889]
rem:  [2 4 6 8]


In [23]:
np.array(range(11))


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.arange(2,11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
from math import pi
import numpy as np
a = np.array([2,4,6,8])
b = np.array([3,5,7,9])
p = np.sin(a)
print(p)

[ 0.90929743 -0.7568025  -0.2794155   0.98935825]


In [28]:
import numpy as np
a = np.linspace(1,12,12)
print("lenght: ", len(a))
print(a)
print(a[5])

lenght:  12
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [38]:
import numpy as np
a = np.array([2,4,6,8])
for index, element in enumerate(a):
    print(index, element)

0 2
1 4
2 6
3 8


In [42]:
for ch in 'good':
    print(ch*2, end='')

ggoooodd